//! Lucide Icons リスト（Obsidianで利用可能なアイコン）。

import { getIconIds } from "obsidian";

//! アイコンカテゴリ。
export interface IconCategory {
	name: string;
	icons: string[];
}

//! Obsidianから動的に取得した全アイコンリスト（キャッシュ）。
let cachedAllIcons: string[] | null = null;

//! Obsidianのlucideアイコンを動的に取得する。
function getAllIconsFromObsidian(): string[] {
	//! 既にキャッシュがある場合は返す。
	if (cachedAllIcons) {
		return cachedAllIcons;
	}

	try {
		//! Obsidian APIの getIconIds() を使用。
		const iconIds = getIconIds();
		console.log(`[memolog] Loaded ${iconIds.length} icons from obsidian.getIconIds()`);
		if (iconIds && iconIds.length > 0) {
			cachedAllIcons = iconIds.sort();
			return cachedAllIcons;
		}
	} catch (error) {
		console.warn("[memolog] Failed to load icons using obsidian.getIconIds():", error);
	}

	//! 動的取得に失敗した場合は、静的リストにフォールバック。
	console.warn("[memolog] Using fallback icon list");
	cachedAllIcons = Array.from(new Set(ICON_CATEGORIES.flatMap((cat) => cat.icons))).sort();
	return cachedAllIcons;
}

//! よく使うアイコン。
export const COMMON_ICONS = [
	"file-text",
	"sticky-note",
	"notebook",
	"book",
	"book-open",
	"briefcase",
	"folder",
	"folder-open",
	"tag",
	"tags",
	"star",
	"heart",
	"home",
	"user",
	"users",
	"clock",
	"calendar",
	"bell",
	"coffee",
	"music",
	"headphones",
	"camera",
	"image",
	"video",
	"film",
	"gamepad-2",
	"puzzle",
	"paintbrush",
	"palette",
	"code",
	"terminal",
	"cpu",
	"database",
	"server",
	"cloud",
	"mail",
	"phone",
	"message-circle",
	"send",
	"shopping-cart",
	"shopping-bag",
	"credit-card",
	"dollar-sign",
	"trending-up",
	"bar-chart",
	"pie-chart",
	"activity",
	"target",
	"flag",
	"bookmark",
	"archive",
	"inbox",
	"layers",
	"package",
	"gift",
	"award",
	"trophy",
	"medal",
	"zap",
	"sun",
	"moon",
	"cloud-rain",
	"umbrella",
	"tree",
	"flower",
	"leaf",
	"bug",
	"bird",
	"dog",
	"cat",
	"fish",
	"pizza",
	"cookie",
	"ice-cream",
	"cake",
	"apple",
	"banana",
	"grape",
	"cherry",
	"strawberry",
	"lemon",
	"carrot",
	"egg",
	"milk",
	"wine",
	"beer",
	"martini",
	"cigarette",
	"bike",
	"car",
	"bus",
	"train",
	"plane",
	"ship",
	"rocket",
	"satellite",
	"anchor",
	"compass",
	"map",
	"map-pin",
	"navigation",
	"locate",
	"globe",
	"landmark",
	"building",
	"store",
	"hospital",
	"school",
	"church",
	"hotel",
	"factory",
	"warehouse",
	"tent",
	"key",
	"lock",
	"unlock",
	"shield",
	"shield-check",
	"eye",
	"eye-off",
	"search",
	"filter",
	"settings",
	"tool",
	"wrench",
	"hammer",
	"scissors",
	"ruler",
	"pen-tool",
	"edit",
	"edit-2",
	"edit-3",
	"trash",
	"trash-2",
	"save",
	"download",
	"upload",
	"share",
	"share-2",
	"link",
	"paperclip",
	"printer",
	"copy",
	"clipboard",
	"check",
	"check-circle",
	"check-square",
	"x",
	"x-circle",
	"x-square",
	"plus",
	"plus-circle",
	"plus-square",
	"minus",
	"minus-circle",
	"minus-square",
	"alert-circle",
	"alert-triangle",
	"alert-octagon",
	"info",
	"help-circle",
	"box",
	"package",
	"codesandbox",
	"feather",
	"pen",
	"pen-line",
	"smile",
	"frown",
	"meh",
	"thumbs-up",
	"thumbs-down",
];

//! カテゴリ別アイコンリスト。
export const ICON_CATEGORIES: IconCategory[] = [
	{
		name: "よく使う",
		icons: COMMON_ICONS.slice(0, 30),
	},
	{
		name: "ドキュメント",
		icons: [
			"file",
			"file-text",
			"file-plus",
			"file-minus",
			"file-edit",
			"file-check",
			"file-x",
			"file-search",
			"file-archive",
			"file-code",
			"file-json",
			"file-spreadsheet",
			"sticky-note",
			"notebook",
			"book",
			"book-open",
			"book-marked",
			"bookmark",
			"bookmark-plus",
			"bookmark-minus",
			"bookmark-check",
			"bookmark-x",
			"library",
			"newspaper",
			"scroll",
			"receipt",
			"clipboard",
			"clipboard-check",
			"clipboard-copy",
			"clipboard-list",
			"clipboard-paste",
			"clipboard-x",
		],
	},
	{
		name: "仕事・ビジネス",
		icons: [
			"briefcase",
			"building",
			"building-2",
			"factory",
			"warehouse",
			"store",
			"landmark",
			"bank",
			"office-building",
			"presentation",
			"chart-line",
			"chart-bar",
			"chart-pie",
			"trending-up",
			"trending-down",
			"activity",
			"target",
			"goal",
			"calculator",
			"calendar",
			"calendar-check",
			"calendar-clock",
			"calendar-days",
			"calendar-plus",
			"calendar-range",
			"calendar-x",
			"clock",
			"timer",
			"alarm-clock",
			"hourglass",
			"dollar-sign",
			"euro",
			"pound-sterling",
			"yen",
			"credit-card",
			"wallet",
			"coins",
			"piggy-bank",
			"banknote",
		],
	},
	{
		name: "フォルダ・整理",
		icons: [
			"folder",
			"folder-open",
			"folder-plus",
			"folder-minus",
			"folder-check",
			"folder-x",
			"folder-search",
			"folder-archive",
			"folder-edit",
			"folder-tree",
			"folders",
			"archive",
			"inbox",
			"package",
			"package-plus",
			"package-minus",
			"package-check",
			"package-x",
			"package-search",
			"box",
			"boxes",
			"container",
			"layers",
			"stack",
			"grid",
			"layout",
			"columns",
			"rows",
			"sidebar",
			"panel-left",
			"panel-right",
		],
	},
	{
		name: "タグ・ラベル",
		icons: [
			"tag",
			"tags",
			"label",
			"hash",
			"at-sign",
			"badge",
			"badge-check",
			"badge-alert",
			"badge-info",
			"badge-help",
			"badge-plus",
			"badge-minus",
			"badge-x",
			"shield",
			"shield-check",
			"shield-alert",
			"shield-x",
			"award",
			"trophy",
			"medal",
			"star",
			"star-half",
			"sparkle",
			"sparkles",
			"crown",
			"gem",
			"diamond",
		],
	},
	{
		name: "人・コミュニケーション",
		icons: [
			"user",
			"user-plus",
			"user-minus",
			"user-check",
			"user-x",
			"users",
			"users-round",
			"contact",
			"id-card",
			"smile",
			"frown",
			"meh",
			"laugh",
			"annoyed",
			"angry",
			"heart",
			"heart-handshake",
			"heart-pulse",
			"message-circle",
			"message-square",
			"mail",
			"inbox",
			"send",
			"phone",
			"phone-call",
			"phone-incoming",
			"phone-outgoing",
			"video",
			"mic",
			"speaker",
			"volume",
			"bell",
			"bell-ring",
		],
	},
	{
		name: "趣味・エンターテイメント",
		icons: [
			"gamepad",
			"gamepad-2",
			"joystick",
			"dice-1",
			"dice-2",
			"dice-3",
			"dice-4",
			"dice-5",
			"dice-6",
			"puzzle",
			"trophy",
			"music",
			"music-2",
			"disc",
			"radio",
			"headphones",
			"mic",
			"guitar",
			"piano",
			"drum",
			"film",
			"video",
			"tv",
			"monitor",
			"popcorn",
			"ticket",
			"palette",
			"paintbrush",
			"brush",
			"pen-tool",
			"camera",
			"image",
			"gallery",
		],
	},
	{
		name: "開発・技術",
		icons: [
			"code",
			"code-2",
			"terminal",
			"cpu",
			"hard-drive",
			"database",
			"server",
			"cloud",
			"cloud-upload",
			"cloud-download",
			"git-branch",
			"git-commit",
			"git-merge",
			"git-pull-request",
			"github",
			"gitlab",
			"package",
			"bug",
			"shield-alert",
			"lock",
			"unlock",
			"key",
			"scan",
			"fingerprint",
			"binary",
			"braces",
			"brackets",
			"regex",
			"function-square",
			"variable",
			"component",
			"blocks",
		],
	},
	{
		name: "自然・天気",
		icons: [
			"sun",
			"moon",
			"cloud",
			"cloud-rain",
			"cloud-snow",
			"cloud-lightning",
			"cloud-fog",
			"wind",
			"snowflake",
			"droplet",
			"droplets",
			"umbrella",
			"rainbow",
			"sunrise",
			"sunset",
			"tree",
			"tree-deciduous",
			"tree-pine",
			"trees",
			"flower",
			"flower-2",
			"leaf",
			"clover",
			"sprout",
			"seedling",
			"mountain",
			"mountain-snow",
			"waves",
			"flame",
			"zap",
		],
	},
	{
		name: "食べ物・飲み物",
		icons: [
			"apple",
			"banana",
			"grape",
			"cherry",
			"strawberry",
			"lemon",
			"orange",
			"pear",
			"peach",
			"watermelon",
			"carrot",
			"corn",
			"egg",
			"croissant",
			"bread",
			"pizza",
			"cookie",
			"donut",
			"cake",
			"ice-cream",
			"ice-cream-2",
			"candy",
			"lollipop",
			"popcorn",
			"milk",
			"coffee",
			"tea",
			"wine",
			"beer",
			"martini",
			"glass-water",
			"soup",
			"utensils",
			"fork-knife",
		],
	},
	{
		name: "乗り物・移動",
		icons: [
			"car",
			"car-front",
			"bus",
			"train",
			"train-front",
			"tram",
			"bike",
			"plane",
			"plane-takeoff",
			"plane-landing",
			"ship",
			"sailboat",
			"ferry",
			"rocket",
			"satellite",
			"anchor",
			"compass",
			"map",
			"map-pin",
			"map-pinned",
			"navigation",
			"navigate",
			"locate",
			"locate-fixed",
			"route",
			"signpost",
			"traffic-cone",
			"fuel",
			"parking-circle",
		],
	},
	{
		name: "場所・建物",
		icons: [
			"home",
			"building",
			"building-2",
			"store",
			"hospital",
			"school",
			"university",
			"church",
			"hotel",
			"factory",
			"warehouse",
			"tent",
			"castle",
			"landmark",
			"bank",
			"library",
			"monument",
			"stadium",
			"tower",
			"lighthouse",
			"bridge",
			"gate",
			"door-open",
			"door-closed",
		],
	},
	{
		name: "動物",
		icons: [
			"bird",
			"dog",
			"cat",
			"rabbit",
			"squirrel",
			"turtle",
			"fish",
			"bug",
			"worm",
			"snail",
			"shell",
			"paw-print",
		],
	},
	{
		name: "ツール・アクション",
		icons: [
			"search",
			"filter",
			"sliders",
			"settings",
			"tool",
			"wrench",
			"hammer",
			"screwdriver",
			"scissors",
			"ruler",
			"pen",
			"pen-line",
			"pen-tool",
			"pencil",
			"edit",
			"edit-2",
			"edit-3",
			"eraser",
			"highlighter",
			"marker",
			"trash",
			"trash-2",
			"recycle",
			"save",
			"download",
			"upload",
			"share",
			"share-2",
			"forward",
			"reply",
			"link",
			"unlink",
			"paperclip",
			"attach",
			"pin",
			"pin-off",
			"printer",
			"scan",
			"copy",
			"clipboard",
			"paste",
			"cut",
			"rotate-cw",
			"rotate-ccw",
			"flip-horizontal",
			"flip-vertical",
			"maximize",
			"minimize",
			"expand",
			"shrink",
			"zoom-in",
			"zoom-out",
			"focus",
			"eye",
			"eye-off",
			"hide",
			"show",
		],
	},
	{
		name: "矢印・ナビゲーション",
		icons: [
			"arrow-up",
			"arrow-down",
			"arrow-left",
			"arrow-right",
			"arrow-up-right",
			"arrow-down-right",
			"arrow-down-left",
			"arrow-up-left",
			"chevron-up",
			"chevron-down",
			"chevron-left",
			"chevron-right",
			"chevrons-up",
			"chevrons-down",
			"chevrons-left",
			"chevrons-right",
			"move",
			"move-diagonal",
			"move-horizontal",
			"move-vertical",
			"corner-down-left",
			"corner-down-right",
			"corner-up-left",
			"corner-up-right",
			"trending-up",
			"trending-down",
		],
	},
	{
		name: "記号・図形",
		icons: [
			"check",
			"check-circle",
			"check-square",
			"x",
			"x-circle",
			"x-square",
			"plus",
			"plus-circle",
			"plus-square",
			"minus",
			"minus-circle",
			"minus-square",
			"equal",
			"alert-circle",
			"alert-triangle",
			"alert-octagon",
			"info",
			"help-circle",
			"circle",
			"circle-dot",
			"square",
			"triangle",
			"hexagon",
			"octagon",
			"diamond",
			"star",
			"heart",
			"infinity",
			"percent",
			"hash",
			"at-sign",
			"asterisk",
			"dollar-sign",
			"quote",
		],
	},
	{
		name: "その他",
		icons: [
			"more-horizontal",
			"more-vertical",
			"menu",
			"grip",
			"grip-horizontal",
			"grip-vertical",
			"separator-horizontal",
			"separator-vertical",
			"loader",
			"loader-2",
			"refresh-cw",
			"refresh-ccw",
			"repeat",
			"shuffle",
			"skip-back",
			"skip-forward",
			"rewind",
			"fast-forward",
			"play",
			"pause",
			"stop",
			"power",
			"power-off",
			"lightbulb",
			"flashlight",
			"battery",
			"battery-charging",
			"plug",
			"magnet",
			"radio",
			"wifi",
			"bluetooth",
			"cast",
			"airplay",
		],
	},
];

//! 全アイコンリストを取得する（動的取得）。
export function getAllIcons(): string[] {
	return getAllIconsFromObsidian();
}

//! アイコン検索関数。
export function searchIcons(query: string, limit = 50): string[] {
	const allIcons = getAllIcons();

	if (!query || query.trim() === "") {
		return allIcons.slice(0, limit);
	}

	const normalizedQuery = query.toLowerCase().trim();

	//! 完全一致を優先。
	const exactMatches = allIcons.filter((icon) => icon === normalizedQuery);

	//! 前方一致。
	const prefixMatches = allIcons.filter(
		(icon) => icon.startsWith(normalizedQuery) && icon !== normalizedQuery
	);

	//! 部分一致。
	const partialMatches = allIcons.filter(
		(icon) => icon.includes(normalizedQuery) && !icon.startsWith(normalizedQuery)
	);

	//! 結果を結合して返す。
	return [...exactMatches, ...prefixMatches, ...partialMatches].slice(0, limit);
}

//! カテゴリからアイコンを取得。
export function getIconsByCategory(categoryName: string): string[] {
	const category = ICON_CATEGORIES.find((cat) => cat.name === categoryName);
	return category ? category.icons : [];
}
